# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(654, 640)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.logo_widget = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_widget.sizePolicy().hasHeightForWidth())
        self.logo_widget.setSizePolicy(sizePolicy)
        self.logo_widget.setMaximumSize(QtCore.QSize(50, 50))
        self.logo_widget.setPixmap(QtGui.QPixmap(":/logo/window_elements/logo.png"))
        self.logo_widget.setScaledContents(True)
        self.logo_widget.setObjectName("logo_widget")
        self.horizontalLayout_9.addWidget(self.logo_widget)
        self.username_label = QtWidgets.QLabel(self.centralwidget)
        self.username_label.setObjectName("username_label")
        self.horizontalLayout_9.addWidget(self.username_label)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.main_menu_button = QtWidgets.QPushButton(self.centralwidget)
        self.main_menu_button.setFlat(True)
        self.main_menu_button.setObjectName("main_menu_button")
        self.horizontalLayout_9.addWidget(self.main_menu_button)
        self.logout_button = QtWidgets.QPushButton(self.centralwidget)
        self.logout_button.setFlat(True)
        self.logout_button.setObjectName("logout_button")
        self.horizontalLayout_9.addWidget(self.logout_button)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_9)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.main_widget = QtWidgets.QStackedWidget(self.centralwidget)
        self.main_widget.setObjectName("main_widget")
        self.login_page = QtWidgets.QWidget()
        self.login_page.setObjectName("login_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.login_page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.login_horizontal_container = QtWidgets.QHBoxLayout()
        self.login_horizontal_container.setObjectName("login_horizontal_container")
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.login_horizontal_container.addItem(spacerItem1)
        self.login_main_layout_2 = QtWidgets.QVBoxLayout()
        self.login_main_layout_2.setObjectName("login_main_layout_2")
        self.login_inputs = QtWidgets.QHBoxLayout()
        self.login_inputs.setObjectName("login_inputs")
        self.login_username_layout = QtWidgets.QVBoxLayout()
        self.login_username_layout.setObjectName("login_username_layout")
        self.login_username_label = QtWidgets.QLabel(self.login_page)
        self.login_username_label.setObjectName("login_username_label")
        self.login_username_layout.addWidget(self.login_username_label)
        self.login_username_input = QtWidgets.QLineEdit(self.login_page)
        self.login_username_input.setObjectName("login_username_input")
        self.login_username_layout.addWidget(self.login_username_input)
        self.login_inputs.addLayout(self.login_username_layout)
        self.login_password_layout = QtWidgets.QVBoxLayout()
        self.login_password_layout.setObjectName("login_password_layout")
        self.login_password_label = QtWidgets.QLabel(self.login_page)
        self.login_password_label.setObjectName("login_password_label")
        self.login_password_layout.addWidget(self.login_password_label)
        self.login_password_input = QtWidgets.QLineEdit(self.login_page)
        self.login_password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.login_password_input.setObjectName("login_password_input")
        self.login_password_layout.addWidget(self.login_password_input)
        self.login_inputs.addLayout(self.login_password_layout)
        self.login_main_layout_2.addLayout(self.login_inputs)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem2)
        self.login_submit_button = QtWidgets.QPushButton(self.login_page)
        self.login_submit_button.setObjectName("login_submit_button")
        self.horizontalLayout_35.addWidget(self.login_submit_button)
        spacerItem3 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem3)
        self.login_main_layout_2.addLayout(self.horizontalLayout_35)
        self.login_success_output = QtWidgets.QLabel(self.login_page)
        self.login_success_output.setObjectName("login_success_output")
        self.login_main_layout_2.addWidget(self.login_success_output)
        self.login_horizontal_container.addLayout(self.login_main_layout_2)
        spacerItem4 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.login_horizontal_container.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.login_horizontal_container)
        spacerItem5 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.login_create_account_button = QtWidgets.QPushButton(self.login_page)
        self.login_create_account_button.setFlat(True)
        self.login_create_account_button.setObjectName("login_create_account_button")
        self.verticalLayout_3.addWidget(self.login_create_account_button)
        self.main_widget.addWidget(self.login_page)
        self.create_account_page = QtWidgets.QWidget()
        self.create_account_page.setObjectName("create_account_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.create_account_page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.create_account_first_name_label = QtWidgets.QLabel(self.create_account_page)
        self.create_account_first_name_label.setObjectName("create_account_first_name_label")
        self.verticalLayout_7.addWidget(self.create_account_first_name_label)
        self.create_account_first_name_input = QtWidgets.QLineEdit(self.create_account_page)
        self.create_account_first_name_input.setObjectName("create_account_first_name_input")
        self.verticalLayout_7.addWidget(self.create_account_first_name_input)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.create_account_last_name_label = QtWidgets.QLabel(self.create_account_page)
        self.create_account_last_name_label.setObjectName("create_account_last_name_label")
        self.verticalLayout_8.addWidget(self.create_account_last_name_label)
        self.create_account_last_name_input = QtWidgets.QLineEdit(self.create_account_page)
        self.create_account_last_name_input.setObjectName("create_account_last_name_input")
        self.verticalLayout_8.addWidget(self.create_account_last_name_input)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.create_account_username_label = QtWidgets.QLabel(self.create_account_page)
        self.create_account_username_label.setObjectName("create_account_username_label")
        self.verticalLayout_5.addWidget(self.create_account_username_label)
        self.create_account_username_input = QtWidgets.QLineEdit(self.create_account_page)
        self.create_account_username_input.setObjectName("create_account_username_input")
        self.verticalLayout_5.addWidget(self.create_account_username_input)
        self.create_account_password_label = QtWidgets.QLabel(self.create_account_page)
        self.create_account_password_label.setObjectName("create_account_password_label")
        self.verticalLayout_5.addWidget(self.create_account_password_label)
        self.create_account_password_input = QtWidgets.QLineEdit(self.create_account_page)
        self.create_account_password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.create_account_password_input.setObjectName("create_account_password_input")
        self.verticalLayout_5.addWidget(self.create_account_password_input)
        self.create_account_verify_password_label = QtWidgets.QLabel(self.create_account_page)
        self.create_account_verify_password_label.setObjectName("create_account_verify_password_label")
        self.verticalLayout_5.addWidget(self.create_account_verify_password_label)
        self.create_account_password_verify_input = QtWidgets.QLineEdit(self.create_account_page)
        self.create_account_password_verify_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.create_account_password_verify_input.setObjectName("create_account_password_verify_input")
        self.verticalLayout_5.addWidget(self.create_account_password_verify_input)
        self.label = QtWidgets.QLabel(self.create_account_page)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.create_account_radio_student = QtWidgets.QRadioButton(self.create_account_page)
        self.create_account_radio_student.setObjectName("create_account_radio_student")
        self.horizontalLayout_6.addWidget(self.create_account_radio_student)
        self.create_account_radio_teacher = QtWidgets.QRadioButton(self.create_account_page)
        self.create_account_radio_teacher.setObjectName("create_account_radio_teacher")
        self.horizontalLayout_6.addWidget(self.create_account_radio_teacher)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem7)
        self.create_account_submit_button = QtWidgets.QPushButton(self.create_account_page)
        self.create_account_submit_button.setObjectName("create_account_submit_button")
        self.horizontalLayout_36.addWidget(self.create_account_submit_button)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_36)
        self.create_account_success_output = QtWidgets.QLabel(self.create_account_page)
        self.create_account_success_output.setObjectName("create_account_success_output")
        self.verticalLayout_5.addWidget(self.create_account_success_output)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        spacerItem9 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        spacerItem10 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem10)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem11 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem11)
        self.create_account_login_button = QtWidgets.QPushButton(self.create_account_page)
        self.create_account_login_button.setFlat(True)
        self.create_account_login_button.setObjectName("create_account_login_button")
        self.horizontalLayout_8.addWidget(self.create_account_login_button)
        spacerItem12 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem12)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.main_widget.addWidget(self.create_account_page)
        self.student_main_menu_page = QtWidgets.QWidget()
        self.student_main_menu_page.setObjectName("student_main_menu_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.student_main_menu_page)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem13 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem13)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.student_main_menu_homework_button = QtWidgets.QPushButton(self.student_main_menu_page)
        self.student_main_menu_homework_button.setObjectName("student_main_menu_homework_button")
        self.verticalLayout_10.addWidget(self.student_main_menu_homework_button)
        self.student_main_menu_previous_scores_button = QtWidgets.QPushButton(self.student_main_menu_page)
        self.student_main_menu_previous_scores_button.setObjectName("student_main_menu_previous_scores_button")
        self.verticalLayout_10.addWidget(self.student_main_menu_previous_scores_button)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        spacerItem14 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem14)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        spacerItem15 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem15)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        spacerItem16 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem16)
        self.student_main_menu_account_management_button = QtWidgets.QPushButton(self.student_main_menu_page)
        self.student_main_menu_account_management_button.setFlat(True)
        self.student_main_menu_account_management_button.setObjectName("student_main_menu_account_management_button")
        self.horizontalLayout_33.addWidget(self.student_main_menu_account_management_button)
        spacerItem17 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem17)
        self.verticalLayout_6.addLayout(self.horizontalLayout_33)
        self.main_widget.addWidget(self.student_main_menu_page)
        self.teacher_main_menu_page = QtWidgets.QWidget()
        self.teacher_main_menu_page.setObjectName("teacher_main_menu_page")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.teacher_main_menu_page)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem18 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem18)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.teacher_main_menu_admin_button = QtWidgets.QPushButton(self.teacher_main_menu_page)
        self.teacher_main_menu_admin_button.setObjectName("teacher_main_menu_admin_button")
        self.verticalLayout_12.addWidget(self.teacher_main_menu_admin_button)
        self.teacher_main_menu_set_homework_button = QtWidgets.QPushButton(self.teacher_main_menu_page)
        self.teacher_main_menu_set_homework_button.setObjectName("teacher_main_menu_set_homework_button")
        self.verticalLayout_12.addWidget(self.teacher_main_menu_set_homework_button)
        self.teacher_main_menu_view_classes_button = QtWidgets.QPushButton(self.teacher_main_menu_page)
        self.teacher_main_menu_view_classes_button.setObjectName("teacher_main_menu_view_classes_button")
        self.verticalLayout_12.addWidget(self.teacher_main_menu_view_classes_button)
        self.horizontalLayout_3.addLayout(self.verticalLayout_12)
        spacerItem19 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem19)
        self.verticalLayout_11.addLayout(self.horizontalLayout_3)
        spacerItem20 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem20)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        spacerItem21 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem21)
        self.teacher_main_menu_account_management_button = QtWidgets.QPushButton(self.teacher_main_menu_page)
        self.teacher_main_menu_account_management_button.setFlat(True)
        self.teacher_main_menu_account_management_button.setObjectName("teacher_main_menu_account_management_button")
        self.horizontalLayout_34.addWidget(self.teacher_main_menu_account_management_button)
        spacerItem22 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem22)
        self.verticalLayout_11.addLayout(self.horizontalLayout_34)
        self.main_widget.addWidget(self.teacher_main_menu_page)
        self.question_page = QtWidgets.QWidget()
        self.question_page.setObjectName("question_page")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.question_page)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.question_topic_output = QtWidgets.QLabel(self.question_page)
        self.question_topic_output.setObjectName("question_topic_output")
        self.verticalLayout_9.addWidget(self.question_topic_output)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem23 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem23)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.question_question_output = QtWidgets.QLabel(self.question_page)
        self.question_question_output.setWordWrap(True)
        self.question_question_output.setObjectName("question_question_output")
        self.verticalLayout_18.addWidget(self.question_question_output)
        self.question_chart = QChartView(self.question_page)
        self.question_chart.setMinimumSize(QtCore.QSize(600, 300))
        self.question_chart.setObjectName("question_chart")
        self.verticalLayout_18.addWidget(self.question_chart)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.question_radio_a = QtWidgets.QRadioButton(self.question_page)
        self.question_radio_a.setObjectName("question_radio_a")
        self.verticalLayout_19.addWidget(self.question_radio_a)
        self.question_radio_b = QtWidgets.QRadioButton(self.question_page)
        self.question_radio_b.setObjectName("question_radio_b")
        self.verticalLayout_19.addWidget(self.question_radio_b)
        self.question_radio_c = QtWidgets.QRadioButton(self.question_page)
        self.question_radio_c.setObjectName("question_radio_c")
        self.verticalLayout_19.addWidget(self.question_radio_c)
        self.question_radio_d = QtWidgets.QRadioButton(self.question_page)
        self.question_radio_d.setObjectName("question_radio_d")
        self.verticalLayout_19.addWidget(self.question_radio_d)
        self.verticalLayout_18.addLayout(self.verticalLayout_19)
        self.verticalLayout_17.addLayout(self.verticalLayout_18)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem24)
        self.question_submit_button = QtWidgets.QPushButton(self.question_page)
        self.question_submit_button.setObjectName("question_submit_button")
        self.horizontalLayout_38.addWidget(self.question_submit_button)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem25)
        self.verticalLayout_17.addLayout(self.horizontalLayout_38)
        self.question_feedback_output = QtWidgets.QLabel(self.question_page)
        self.question_feedback_output.setObjectName("question_feedback_output")
        self.verticalLayout_17.addWidget(self.question_feedback_output)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem26 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem26)
        self.question_previous_question_button = QtWidgets.QPushButton(self.question_page)
        self.question_previous_question_button.setEnabled(True)
        self.question_previous_question_button.setObjectName("question_previous_question_button")
        self.horizontalLayout.addWidget(self.question_previous_question_button)
        self.question_next_question_button = QtWidgets.QPushButton(self.question_page)
        self.question_next_question_button.setEnabled(True)
        self.question_next_question_button.setObjectName("question_next_question_button")
        self.horizontalLayout.addWidget(self.question_next_question_button)
        spacerItem27 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem27)
        self.verticalLayout_17.addLayout(self.horizontalLayout)
        self.horizontalLayout_10.addLayout(self.verticalLayout_17)
        spacerItem28 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem28)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        spacerItem29 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem29)
        self.main_widget.addWidget(self.question_page)
        self.homework_select_page = QtWidgets.QWidget()
        self.homework_select_page.setObjectName("homework_select_page")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.homework_select_page)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        spacerItem30 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem30)
        self.verticalLayout_45 = QtWidgets.QVBoxLayout()
        self.verticalLayout_45.setObjectName("verticalLayout_45")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.homework_select_class_combo_box = QtWidgets.QComboBox(self.homework_select_page)
        self.homework_select_class_combo_box.setObjectName("homework_select_class_combo_box")
        self.homework_select_class_combo_box.addItem("")
        self.horizontalLayout_29.addWidget(self.homework_select_class_combo_box)
        spacerItem31 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem31)
        self.verticalLayout_45.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.homework_select_table = QtWidgets.QTableWidget(self.homework_select_page)
        self.homework_select_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.homework_select_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.homework_select_table.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.homework_select_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.homework_select_table.setObjectName("homework_select_table")
        self.homework_select_table.setColumnCount(2)
        self.homework_select_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.homework_select_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.homework_select_table.setHorizontalHeaderItem(1, item)
        self.verticalLayout_2.addWidget(self.homework_select_table)
        spacerItem32 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem32)
        self.horizontalLayout_37.addLayout(self.verticalLayout_2)
        spacerItem33 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_37.addItem(spacerItem33)
        self.verticalLayout_45.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_28.addLayout(self.verticalLayout_45)
        spacerItem34 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem34)
        self.verticalLayout_16.addLayout(self.horizontalLayout_28)
        spacerItem35 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem35)
        self.main_widget.addWidget(self.homework_select_page)
        self.previous_scores_page = QtWidgets.QWidget()
        self.previous_scores_page.setObjectName("previous_scores_page")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.previous_scores_page)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem36 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem36)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.previous_scores_class_combo_box = QtWidgets.QComboBox(self.previous_scores_page)
        self.previous_scores_class_combo_box.setObjectName("previous_scores_class_combo_box")
        self.previous_scores_class_combo_box.addItem("")
        self.horizontalLayout_12.addWidget(self.previous_scores_class_combo_box)
        spacerItem37 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem37)
        self.verticalLayout_25.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.previous_scores_table = QtWidgets.QTableWidget(self.previous_scores_page)
        self.previous_scores_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.previous_scores_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.previous_scores_table.setObjectName("previous_scores_table")
        self.previous_scores_table.setColumnCount(3)
        self.previous_scores_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.previous_scores_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.previous_scores_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.previous_scores_table.setHorizontalHeaderItem(2, item)
        self.verticalLayout_24.addWidget(self.previous_scores_table)
        spacerItem38 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_24.addItem(spacerItem38)
        self.horizontalLayout_14.addLayout(self.verticalLayout_24)
        spacerItem39 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem39)
        self.verticalLayout_25.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_7.addLayout(self.verticalLayout_25)
        spacerItem40 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem40)
        self.verticalLayout_15.addLayout(self.horizontalLayout_7)
        spacerItem41 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem41)
        self.main_widget.addWidget(self.previous_scores_page)
        self.set_homework_page = QtWidgets.QWidget()
        self.set_homework_page.setObjectName("set_homework_page")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.set_homework_page)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        spacerItem42 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem42)
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.label_6 = QtWidgets.QLabel(self.set_homework_page)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_33.addWidget(self.label_6)
        self.set_homework_class_combo_box = QtWidgets.QComboBox(self.set_homework_page)
        self.set_homework_class_combo_box.setObjectName("set_homework_class_combo_box")
        self.verticalLayout_33.addWidget(self.set_homework_class_combo_box)
        self.label_9 = QtWidgets.QLabel(self.set_homework_page)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_33.addWidget(self.label_9)
        self.set_homework_homework_combo_box = QtWidgets.QComboBox(self.set_homework_page)
        self.set_homework_homework_combo_box.setObjectName("set_homework_homework_combo_box")
        self.verticalLayout_33.addWidget(self.set_homework_homework_combo_box)
        self.set_homework_tab_widget = QtWidgets.QTabWidget(self.set_homework_page)
        self.set_homework_tab_widget.setObjectName("set_homework_tab_widget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_56 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_56.setObjectName("verticalLayout_56")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_35.addWidget(self.label_8)
        self.set_homework_type_combo_box = QtWidgets.QComboBox(self.tab)
        self.set_homework_type_combo_box.setObjectName("set_homework_type_combo_box")
        self.set_homework_type_combo_box.addItem("")
        self.set_homework_type_combo_box.addItem("")
        self.set_homework_type_combo_box.addItem("")
        self.set_homework_type_combo_box.addItem("")
        self.set_homework_type_combo_box.addItem("")
        self.verticalLayout_35.addWidget(self.set_homework_type_combo_box)
        self.horizontalLayout_26.addLayout(self.verticalLayout_35)
        self.verticalLayout_36 = QtWidgets.QVBoxLayout()
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_36.addWidget(self.label_10)
        self.set_homework_difficulty_combo_box = QtWidgets.QComboBox(self.tab)
        self.set_homework_difficulty_combo_box.setObjectName("set_homework_difficulty_combo_box")
        self.set_homework_difficulty_combo_box.addItem("")
        self.set_homework_difficulty_combo_box.addItem("")
        self.set_homework_difficulty_combo_box.addItem("")
        self.set_homework_difficulty_combo_box.addItem("")
        self.set_homework_difficulty_combo_box.addItem("")
        self.verticalLayout_36.addWidget(self.set_homework_difficulty_combo_box)
        self.horizontalLayout_26.addLayout(self.verticalLayout_36)
        self.verticalLayout_56.addLayout(self.horizontalLayout_26)
        self.set_homework_add_automatic_question_button = QtWidgets.QPushButton(self.tab)
        self.set_homework_add_automatic_question_button.setObjectName("set_homework_add_automatic_question_button")
        self.verticalLayout_56.addWidget(self.set_homework_add_automatic_question_button)
        self.set_homework_auto_question_added_output = QtWidgets.QLabel(self.tab)
        self.set_homework_auto_question_added_output.setAlignment(QtCore.Qt.AlignCenter)
        self.set_homework_auto_question_added_output.setObjectName("set_homework_auto_question_added_output")
        self.verticalLayout_56.addWidget(self.set_homework_auto_question_added_output)
        spacerItem43 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_56.addItem(spacerItem43)
        self.set_homework_tab_widget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_57 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_57.setObjectName("verticalLayout_57")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_57.addWidget(self.label_21)
        self.set_homework_question_name_input = QtWidgets.QLineEdit(self.tab_2)
        self.set_homework_question_name_input.setObjectName("set_homework_question_name_input")
        self.verticalLayout_57.addWidget(self.set_homework_question_name_input)
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_57.addWidget(self.label_11)
        self.set_homework_question_input = QtWidgets.QTextEdit(self.tab_2)
        self.set_homework_question_input.setObjectName("set_homework_question_input")
        self.verticalLayout_57.addWidget(self.set_homework_question_input)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout()
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_39.addWidget(self.label_12)
        self.set_homework_correct_answer_input = QtWidgets.QTextEdit(self.tab_2)
        self.set_homework_correct_answer_input.setObjectName("set_homework_correct_answer_input")
        self.verticalLayout_39.addWidget(self.set_homework_correct_answer_input)
        self.horizontalLayout_27.addLayout(self.verticalLayout_39)
        self.verticalLayout_40 = QtWidgets.QVBoxLayout()
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_40.addWidget(self.label_13)
        self.set_homework_answer_b_input = QtWidgets.QTextEdit(self.tab_2)
        self.set_homework_answer_b_input.setObjectName("set_homework_answer_b_input")
        self.verticalLayout_40.addWidget(self.set_homework_answer_b_input)
        self.horizontalLayout_27.addLayout(self.verticalLayout_40)
        self.verticalLayout_41 = QtWidgets.QVBoxLayout()
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_41.addWidget(self.label_18)
        self.set_homework_answer_c_input = QtWidgets.QTextEdit(self.tab_2)
        self.set_homework_answer_c_input.setObjectName("set_homework_answer_c_input")
        self.verticalLayout_41.addWidget(self.set_homework_answer_c_input)
        self.horizontalLayout_27.addLayout(self.verticalLayout_41)
        self.verticalLayout_42 = QtWidgets.QVBoxLayout()
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_42.addWidget(self.label_19)
        self.set_homework_answer_d_input = QtWidgets.QTextEdit(self.tab_2)
        self.set_homework_answer_d_input.setObjectName("set_homework_answer_d_input")
        self.verticalLayout_42.addWidget(self.set_homework_answer_d_input)
        self.horizontalLayout_27.addLayout(self.verticalLayout_42)
        self.verticalLayout_57.addLayout(self.horizontalLayout_27)
        self.set_homework_add_custom_question_button = QtWidgets.QPushButton(self.tab_2)
        self.set_homework_add_custom_question_button.setObjectName("set_homework_add_custom_question_button")
        self.verticalLayout_57.addWidget(self.set_homework_add_custom_question_button)
        self.set_homework_custom_question_added_output = QtWidgets.QLabel(self.tab_2)
        self.set_homework_custom_question_added_output.setAlignment(QtCore.Qt.AlignCenter)
        self.set_homework_custom_question_added_output.setObjectName("set_homework_custom_question_added_output")
        self.verticalLayout_57.addWidget(self.set_homework_custom_question_added_output)
        spacerItem44 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_57.addItem(spacerItem44)
        self.set_homework_tab_widget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_58 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_58.setObjectName("verticalLayout_58")
        self.set_homework_question_combo_box = QtWidgets.QComboBox(self.tab_3)
        self.set_homework_question_combo_box.setObjectName("set_homework_question_combo_box")
        self.verticalLayout_58.addWidget(self.set_homework_question_combo_box)
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_58.addWidget(self.label_7)
        self.set_homework_question_label = QtWidgets.QLabel(self.tab_3)
        self.set_homework_question_label.setWordWrap(True)
        self.set_homework_question_label.setObjectName("set_homework_question_label")
        self.verticalLayout_58.addWidget(self.set_homework_question_label)
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_58.addWidget(self.label_5)
        self.set_homework_answer_label = QtWidgets.QLabel(self.tab_3)
        self.set_homework_answer_label.setWordWrap(True)
        self.set_homework_answer_label.setObjectName("set_homework_answer_label")
        self.verticalLayout_58.addWidget(self.set_homework_answer_label)
        self.set_homework_remove_question_button = QtWidgets.QPushButton(self.tab_3)
        self.set_homework_remove_question_button.setObjectName("set_homework_remove_question_button")
        self.verticalLayout_58.addWidget(self.set_homework_remove_question_button)
        self.set_homework_removed_output = QtWidgets.QLabel(self.tab_3)
        self.set_homework_removed_output.setAlignment(QtCore.Qt.AlignCenter)
        self.set_homework_removed_output.setObjectName("set_homework_removed_output")
        self.verticalLayout_58.addWidget(self.set_homework_removed_output)
        spacerItem45 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_58.addItem(spacerItem45)
        self.set_homework_tab_widget.addTab(self.tab_3, "")
        self.verticalLayout_33.addWidget(self.set_homework_tab_widget)
        self.horizontalLayout_25.addLayout(self.verticalLayout_33)
        spacerItem46 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem46)
        self.verticalLayout_20.addLayout(self.horizontalLayout_25)
        spacerItem47 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_20.addItem(spacerItem47)
        self.main_widget.addWidget(self.set_homework_page)
        self.admin_page = QtWidgets.QWidget()
        self.admin_page.setObjectName("admin_page")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.admin_page)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem48 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem48)
        self.verticalLayout_67 = QtWidgets.QVBoxLayout()
        self.verticalLayout_67.setObjectName("verticalLayout_67")
        self.label_16 = QtWidgets.QLabel(self.admin_page)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_67.addWidget(self.label_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.admin_class_input = QtWidgets.QLineEdit(self.admin_page)
        self.admin_class_input.setText("")
        self.admin_class_input.setObjectName("admin_class_input")
        self.horizontalLayout_17.addWidget(self.admin_class_input)
        self.admin_create_class_submit_button = QtWidgets.QPushButton(self.admin_page)
        self.admin_create_class_submit_button.setObjectName("admin_create_class_submit_button")
        self.horizontalLayout_17.addWidget(self.admin_create_class_submit_button)
        self.verticalLayout_67.addLayout(self.horizontalLayout_17)
        self.admin_create_class_status_label = QtWidgets.QLabel(self.admin_page)
        self.admin_create_class_status_label.setObjectName("admin_create_class_status_label")
        self.verticalLayout_67.addWidget(self.admin_create_class_status_label)
        spacerItem49 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_67.addItem(spacerItem49)
        self.label_14 = QtWidgets.QLabel(self.admin_page)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_67.addWidget(self.label_14)
        self.verticalLayout_68 = QtWidgets.QVBoxLayout()
        self.verticalLayout_68.setObjectName("verticalLayout_68")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.admin_class_user_combo_box = QtWidgets.QComboBox(self.admin_page)
        self.admin_class_user_combo_box.setObjectName("admin_class_user_combo_box")
        self.admin_class_user_combo_box.addItem("")
        self.horizontalLayout_31.addWidget(self.admin_class_user_combo_box)
        spacerItem50 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem50)
        self.verticalLayout_68.addLayout(self.horizontalLayout_31)
        self.verticalLayout_67.addLayout(self.verticalLayout_68)
        self.admin_tab_widget = QtWidgets.QTabWidget(self.admin_page)
        self.admin_tab_widget.setObjectName("admin_tab_widget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.admin_username_input = QtWidgets.QLineEdit(self.tab_5)
        self.admin_username_input.setText("")
        self.admin_username_input.setObjectName("admin_username_input")
        self.horizontalLayout_15.addWidget(self.admin_username_input)
        self.admin_username_submit_button = QtWidgets.QPushButton(self.tab_5)
        self.admin_username_submit_button.setObjectName("admin_username_submit_button")
        self.horizontalLayout_15.addWidget(self.admin_username_submit_button)
        self.verticalLayout_26.addLayout(self.horizontalLayout_15)
        self.admin_add_user_status_label = QtWidgets.QLabel(self.tab_5)
        self.admin_add_user_status_label.setObjectName("admin_add_user_status_label")
        self.verticalLayout_26.addWidget(self.admin_add_user_status_label)
        spacerItem51 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_26.addItem(spacerItem51)
        self.admin_tab_widget.addTab(self.tab_5, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_55 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_55.setObjectName("verticalLayout_55")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.admin_username_combo_box = QtWidgets.QComboBox(self.tab_4)
        self.admin_username_combo_box.setObjectName("admin_username_combo_box")
        self.admin_username_combo_box.addItem("")
        self.horizontalLayout_16.addWidget(self.admin_username_combo_box)
        self.admin_remove_user_button = QtWidgets.QPushButton(self.tab_4)
        self.admin_remove_user_button.setObjectName("admin_remove_user_button")
        self.horizontalLayout_16.addWidget(self.admin_remove_user_button)
        self.verticalLayout_55.addLayout(self.horizontalLayout_16)
        self.admin_remove_user_status_label = QtWidgets.QLabel(self.tab_4)
        self.admin_remove_user_status_label.setObjectName("admin_remove_user_status_label")
        self.verticalLayout_55.addWidget(self.admin_remove_user_status_label)
        spacerItem52 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_55.addItem(spacerItem52)
        self.admin_tab_widget.addTab(self.tab_4, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_60 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_60.setObjectName("verticalLayout_60")
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.verticalLayout_69 = QtWidgets.QVBoxLayout()
        self.verticalLayout_69.setObjectName("verticalLayout_69")
        self.label_42 = QtWidgets.QLabel(self.tab_6)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_69.addWidget(self.label_42)
        self.admin_homework_name_input = QtWidgets.QLineEdit(self.tab_6)
        self.admin_homework_name_input.setObjectName("admin_homework_name_input")
        self.verticalLayout_69.addWidget(self.admin_homework_name_input)
        self.label_3 = QtWidgets.QLabel(self.tab_6)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_69.addWidget(self.label_3)
        self.admin_homework_description_input = QtWidgets.QTextEdit(self.tab_6)
        self.admin_homework_description_input.setObjectName("admin_homework_description_input")
        self.verticalLayout_69.addWidget(self.admin_homework_description_input)
        self.horizontalLayout_42.addLayout(self.verticalLayout_69)
        spacerItem53 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_42.addItem(spacerItem53)
        self.verticalLayout_70 = QtWidgets.QVBoxLayout()
        self.verticalLayout_70.setObjectName("verticalLayout_70")
        self.label_43 = QtWidgets.QLabel(self.tab_6)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_70.addWidget(self.label_43)
        self.admin_due_date_calendar = QtWidgets.QCalendarWidget(self.tab_6)
        self.admin_due_date_calendar.setObjectName("admin_due_date_calendar")
        self.verticalLayout_70.addWidget(self.admin_due_date_calendar)
        self.horizontalLayout_42.addLayout(self.verticalLayout_70)
        self.verticalLayout_60.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        spacerItem54 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem54)
        self.admin_add_homework_button = QtWidgets.QPushButton(self.tab_6)
        self.admin_add_homework_button.setObjectName("admin_add_homework_button")
        self.horizontalLayout_30.addWidget(self.admin_add_homework_button)
        spacerItem55 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem55)
        self.verticalLayout_60.addLayout(self.horizontalLayout_30)
        self.admin_add_homework_status_output = QtWidgets.QLabel(self.tab_6)
        self.admin_add_homework_status_output.setAlignment(QtCore.Qt.AlignCenter)
        self.admin_add_homework_status_output.setObjectName("admin_add_homework_status_output")
        self.verticalLayout_60.addWidget(self.admin_add_homework_status_output)
        spacerItem56 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_60.addItem(spacerItem56)
        self.admin_tab_widget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_61 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_61.setObjectName("verticalLayout_61")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.admin_remove_homework_combo_box = QtWidgets.QComboBox(self.tab_7)
        self.admin_remove_homework_combo_box.setObjectName("admin_remove_homework_combo_box")
        self.admin_remove_homework_combo_box.addItem("")
        self.horizontalLayout_32.addWidget(self.admin_remove_homework_combo_box)
        self.admin_remove_homework_button = QtWidgets.QPushButton(self.tab_7)
        self.admin_remove_homework_button.setObjectName("admin_remove_homework_button")
        self.horizontalLayout_32.addWidget(self.admin_remove_homework_button)
        self.verticalLayout_61.addLayout(self.horizontalLayout_32)
        self.admin_remove_homework_status_label = QtWidgets.QLabel(self.tab_7)
        self.admin_remove_homework_status_label.setObjectName("admin_remove_homework_status_label")
        self.verticalLayout_61.addWidget(self.admin_remove_homework_status_label)
        spacerItem57 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_61.addItem(spacerItem57)
        self.admin_tab_widget.addTab(self.tab_7, "")
        self.verticalLayout_67.addWidget(self.admin_tab_widget)
        self.horizontalLayout_13.addLayout(self.verticalLayout_67)
        spacerItem58 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem58)
        self.verticalLayout_21.addLayout(self.horizontalLayout_13)
        spacerItem59 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem59)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        spacerItem60 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_41.addItem(spacerItem60)
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_20 = QtWidgets.QLabel(self.admin_page)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_27.addWidget(self.label_20)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.admin_delete_class_combo_box = QtWidgets.QComboBox(self.admin_page)
        self.admin_delete_class_combo_box.setObjectName("admin_delete_class_combo_box")
        self.admin_delete_class_combo_box.addItem("")
        self.horizontalLayout_18.addWidget(self.admin_delete_class_combo_box)
        self.admin_remove_class_button = QtWidgets.QPushButton(self.admin_page)
        self.admin_remove_class_button.setObjectName("admin_remove_class_button")
        self.horizontalLayout_18.addWidget(self.admin_remove_class_button)
        self.verticalLayout_27.addLayout(self.horizontalLayout_18)
        self.admin_delete_class_status_label = QtWidgets.QLabel(self.admin_page)
        self.admin_delete_class_status_label.setObjectName("admin_delete_class_status_label")
        self.verticalLayout_27.addWidget(self.admin_delete_class_status_label)
        self.horizontalLayout_41.addLayout(self.verticalLayout_27)
        spacerItem61 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_41.addItem(spacerItem61)
        self.verticalLayout_21.addLayout(self.horizontalLayout_41)
        self.main_widget.addWidget(self.admin_page)
        self.account_management_page = QtWidgets.QWidget()
        self.account_management_page.setObjectName("account_management_page")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.account_management_page)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem62 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem62)
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.account_management_first_name_label = QtWidgets.QLabel(self.account_management_page)
        self.account_management_first_name_label.setObjectName("account_management_first_name_label")
        self.verticalLayout_30.addWidget(self.account_management_first_name_label)
        self.account_management_first_name_input = QtWidgets.QLineEdit(self.account_management_page)
        self.account_management_first_name_input.setObjectName("account_management_first_name_input")
        self.verticalLayout_30.addWidget(self.account_management_first_name_input)
        self.horizontalLayout_20.addLayout(self.verticalLayout_30)
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.account_management_last_name_label = QtWidgets.QLabel(self.account_management_page)
        self.account_management_last_name_label.setObjectName("account_management_last_name_label")
        self.verticalLayout_31.addWidget(self.account_management_last_name_label)
        self.account_management_last_name_input = QtWidgets.QLineEdit(self.account_management_page)
        self.account_management_last_name_input.setObjectName("account_management_last_name_input")
        self.verticalLayout_31.addWidget(self.account_management_last_name_input)
        self.horizontalLayout_20.addLayout(self.verticalLayout_31)
        self.verticalLayout_29.addLayout(self.horizontalLayout_20)
        self.account_management_old_password_label = QtWidgets.QLabel(self.account_management_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.account_management_old_password_label.sizePolicy().hasHeightForWidth())
        self.account_management_old_password_label.setSizePolicy(sizePolicy)
        self.account_management_old_password_label.setObjectName("account_management_old_password_label")
        self.verticalLayout_29.addWidget(self.account_management_old_password_label)
        self.account_management_old_password_input = QtWidgets.QLineEdit(self.account_management_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.account_management_old_password_input.sizePolicy().hasHeightForWidth())
        self.account_management_old_password_input.setSizePolicy(sizePolicy)
        self.account_management_old_password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.account_management_old_password_input.setObjectName("account_management_old_password_input")
        self.verticalLayout_29.addWidget(self.account_management_old_password_input)
        self.account_management_new_password_label = QtWidgets.QLabel(self.account_management_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.account_management_new_password_label.sizePolicy().hasHeightForWidth())
        self.account_management_new_password_label.setSizePolicy(sizePolicy)
        self.account_management_new_password_label.setObjectName("account_management_new_password_label")
        self.verticalLayout_29.addWidget(self.account_management_new_password_label)
        self.account_management_new_password_input = QtWidgets.QLineEdit(self.account_management_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.account_management_new_password_input.sizePolicy().hasHeightForWidth())
        self.account_management_new_password_input.setSizePolicy(sizePolicy)
        self.account_management_new_password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.account_management_new_password_input.setObjectName("account_management_new_password_input")
        self.verticalLayout_29.addWidget(self.account_management_new_password_input)
        self.account_management_verify_new_password_label = QtWidgets.QLabel(self.account_management_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.account_management_verify_new_password_label.sizePolicy().hasHeightForWidth())
        self.account_management_verify_new_password_label.setSizePolicy(sizePolicy)
        self.account_management_verify_new_password_label.setObjectName("account_management_verify_new_password_label")
        self.verticalLayout_29.addWidget(self.account_management_verify_new_password_label)
        self.account_management_new_password_verify_input = QtWidgets.QLineEdit(self.account_management_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.account_management_new_password_verify_input.sizePolicy().hasHeightForWidth())
        self.account_management_new_password_verify_input.setSizePolicy(sizePolicy)
        self.account_management_new_password_verify_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.account_management_new_password_verify_input.setObjectName("account_management_new_password_verify_input")
        self.verticalLayout_29.addWidget(self.account_management_new_password_verify_input)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        spacerItem63 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem63)
        self.account_management_submit_button = QtWidgets.QPushButton(self.account_management_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.account_management_submit_button.sizePolicy().hasHeightForWidth())
        self.account_management_submit_button.setSizePolicy(sizePolicy)
        self.account_management_submit_button.setObjectName("account_management_submit_button")
        self.horizontalLayout_39.addWidget(self.account_management_submit_button)
        spacerItem64 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem64)
        self.verticalLayout_29.addLayout(self.horizontalLayout_39)
        self.account_management_success_output = QtWidgets.QLabel(self.account_management_page)
        self.account_management_success_output.setObjectName("account_management_success_output")
        self.verticalLayout_29.addWidget(self.account_management_success_output)
        self.horizontalLayout_19.addLayout(self.verticalLayout_29)
        spacerItem65 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem65)
        self.verticalLayout_22.addLayout(self.horizontalLayout_19)
        spacerItem66 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_22.addItem(spacerItem66)
        self.main_widget.addWidget(self.account_management_page)
        self.view_classes_page = QtWidgets.QWidget()
        self.view_classes_page.setObjectName("view_classes_page")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.view_classes_page)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem67 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem67)
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.label_15 = QtWidgets.QLabel(self.view_classes_page)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_32.addWidget(self.label_15)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.view_classes_view_type_combo_box = QtWidgets.QComboBox(self.view_classes_page)
        self.view_classes_view_type_combo_box.setObjectName("view_classes_view_type_combo_box")
        self.view_classes_view_type_combo_box.addItem("")
        self.view_classes_view_type_combo_box.addItem("")
        self.horizontalLayout_22.addWidget(self.view_classes_view_type_combo_box)
        spacerItem68 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem68)
        self.verticalLayout_32.addLayout(self.horizontalLayout_22)
        self.label_17 = QtWidgets.QLabel(self.view_classes_page)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_32.addWidget(self.label_17)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.view_classes_class_combo_box = QtWidgets.QComboBox(self.view_classes_page)
        self.view_classes_class_combo_box.setObjectName("view_classes_class_combo_box")
        self.horizontalLayout_23.addWidget(self.view_classes_class_combo_box)
        spacerItem69 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem69)
        self.verticalLayout_32.addLayout(self.horizontalLayout_23)
        self.view_classes_display_type_output = QtWidgets.QLabel(self.view_classes_page)
        self.view_classes_display_type_output.setObjectName("view_classes_display_type_output")
        self.verticalLayout_32.addWidget(self.view_classes_display_type_output)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.view_classes_homework_or_student_combo_box = QtWidgets.QComboBox(self.view_classes_page)
        self.view_classes_homework_or_student_combo_box.setCurrentText("")
        self.view_classes_homework_or_student_combo_box.setObjectName("view_classes_homework_or_student_combo_box")
        self.horizontalLayout_24.addWidget(self.view_classes_homework_or_student_combo_box)
        spacerItem70 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem70)
        self.verticalLayout_32.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.view_classes_score_table = QtWidgets.QTableWidget(self.view_classes_page)
        self.view_classes_score_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.view_classes_score_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.view_classes_score_table.setObjectName("view_classes_score_table")
        self.view_classes_score_table.setColumnCount(0)
        self.view_classes_score_table.setRowCount(0)
        self.verticalLayout_13.addWidget(self.view_classes_score_table)
        spacerItem71 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem71)
        self.horizontalLayout_40.addLayout(self.verticalLayout_13)
        spacerItem72 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem72)
        self.verticalLayout_32.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_21.addLayout(self.verticalLayout_32)
        spacerItem73 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem73)
        self.verticalLayout_23.addLayout(self.horizontalLayout_21)
        spacerItem74 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_23.addItem(spacerItem74)
        self.main_widget.addWidget(self.view_classes_page)
        self.verticalLayout.addWidget(self.main_widget)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.login_username_label.setBuddy(self.login_username_input)
        self.login_password_label.setBuddy(self.login_password_input)
        self.login_success_output.setBuddy(self.login_submit_button)

        self.retranslateUi(MainWindow)
        self.main_widget.setCurrentIndex(7)
        self.set_homework_tab_widget.setCurrentIndex(0)
        self.admin_tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Coursework"))
        self.username_label.setText(_translate("MainWindow", "Usernamexx"))
        self.main_menu_button.setText(_translate("MainWindow", "Main Menu"))
        self.logout_button.setText(_translate("MainWindow", "Logout"))
        self.login_username_label.setText(_translate("MainWindow", "Username"))
        self.login_username_input.setPlaceholderText(_translate("MainWindow", "Username"))
        self.login_password_label.setText(_translate("MainWindow", "Password"))
        self.login_password_input.setPlaceholderText(_translate("MainWindow", "Password"))
        self.login_submit_button.setText(_translate("MainWindow", "Submit"))
        self.login_success_output.setText(_translate("MainWindow", "Result"))
        self.login_create_account_button.setText(_translate("MainWindow", "Create Account"))
        self.create_account_first_name_label.setText(_translate("MainWindow", "First Name"))
        self.create_account_first_name_input.setPlaceholderText(_translate("MainWindow", "First Name"))
        self.create_account_last_name_label.setText(_translate("MainWindow", "Last Name"))
        self.create_account_last_name_input.setPlaceholderText(_translate("MainWindow", "Last Name"))
        self.create_account_username_label.setText(_translate("MainWindow", "Username:"))
        self.create_account_username_input.setPlaceholderText(_translate("MainWindow", "Username"))
        self.create_account_password_label.setText(_translate("MainWindow", "Password:"))
        self.create_account_password_input.setPlaceholderText(_translate("MainWindow", "Password"))
        self.create_account_verify_password_label.setText(_translate("MainWindow", "Verify Password:"))
        self.create_account_password_verify_input.setPlaceholderText(_translate("MainWindow", "Verify Password"))
        self.label.setText(_translate("MainWindow", "User Type:"))
        self.create_account_radio_student.setText(_translate("MainWindow", "Student"))
        self.create_account_radio_teacher.setText(_translate("MainWindow", "Teacher"))
        self.create_account_submit_button.setText(_translate("MainWindow", "Submit"))
        self.create_account_success_output.setText(_translate("MainWindow", "Result"))
        self.create_account_login_button.setText(_translate("MainWindow", "Login"))
        self.student_main_menu_homework_button.setText(_translate("MainWindow", "Homework"))
        self.student_main_menu_previous_scores_button.setText(_translate("MainWindow", "Scores"))
        self.student_main_menu_account_management_button.setText(_translate("MainWindow", "Account Management"))
        self.teacher_main_menu_admin_button.setText(_translate("MainWindow", "Class Management"))
        self.teacher_main_menu_set_homework_button.setText(_translate("MainWindow", "Homework Management"))
        self.teacher_main_menu_view_classes_button.setText(_translate("MainWindow", "Scores"))
        self.teacher_main_menu_account_management_button.setText(_translate("MainWindow", "Account Management"))
        self.question_topic_output.setText(_translate("MainWindow", "Topic"))
        self.question_question_output.setText(_translate("MainWindow", "Question"))
        self.question_radio_a.setText(_translate("MainWindow", "Answer A"))
        self.question_radio_b.setText(_translate("MainWindow", "Answer B"))
        self.question_radio_c.setText(_translate("MainWindow", "Answer C"))
        self.question_radio_d.setText(_translate("MainWindow", "Answer D"))
        self.question_submit_button.setText(_translate("MainWindow", "Submit"))
        self.question_feedback_output.setText(_translate("MainWindow", "Feedback"))
        self.question_previous_question_button.setText(_translate("MainWindow", "Previous Question"))
        self.question_next_question_button.setText(_translate("MainWindow", "Next Question"))
        self.homework_select_class_combo_box.setItemText(0, _translate("MainWindow", "Class"))
        self.homework_select_table.setSortingEnabled(True)
        item = self.homework_select_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Homework"))
        item = self.homework_select_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Due Date"))
        self.previous_scores_class_combo_box.setItemText(0, _translate("MainWindow", "Class"))
        self.previous_scores_table.setSortingEnabled(True)
        item = self.previous_scores_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Homework"))
        item = self.previous_scores_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Score"))
        item = self.previous_scores_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Date"))
        self.label_6.setText(_translate("MainWindow", "Select Class:"))
        self.label_9.setText(_translate("MainWindow", "Select Homework"))
        self.label_8.setText(_translate("MainWindow", "Question Type:"))
        self.set_homework_type_combo_box.setItemText(0, _translate("MainWindow", "Find resultant of two forces"))
        self.set_homework_type_combo_box.setItemText(1, _translate("MainWindow", "Simpson\'s Rule"))
        self.set_homework_type_combo_box.setItemText(2, _translate("MainWindow", "Trapezium Rule"))
        self.set_homework_type_combo_box.setItemText(3, _translate("MainWindow", "Definite Integral"))
        self.set_homework_type_combo_box.setItemText(4, _translate("MainWindow", "Projectile"))
        self.label_10.setText(_translate("MainWindow", "Difficulty:"))
        self.set_homework_difficulty_combo_box.setItemText(0, _translate("MainWindow", "1"))
        self.set_homework_difficulty_combo_box.setItemText(1, _translate("MainWindow", "2"))
        self.set_homework_difficulty_combo_box.setItemText(2, _translate("MainWindow", "3"))
        self.set_homework_difficulty_combo_box.setItemText(3, _translate("MainWindow", "4"))
        self.set_homework_difficulty_combo_box.setItemText(4, _translate("MainWindow", "5"))
        self.set_homework_add_automatic_question_button.setText(_translate("MainWindow", "Add Automatic Question"))
        self.set_homework_auto_question_added_output.setText(_translate("MainWindow", "Question Added"))
        self.set_homework_tab_widget.setTabText(self.set_homework_tab_widget.indexOf(self.tab), _translate("MainWindow", "Add Automatic Question"))
        self.label_21.setText(_translate("MainWindow", "Question Name:"))
        self.set_homework_question_name_input.setPlaceholderText(_translate("MainWindow", "Question Name"))
        self.label_11.setText(_translate("MainWindow", "Question:"))
        self.set_homework_question_input.setPlaceholderText(_translate("MainWindow", "Question Text"))
        self.label_12.setText(_translate("MainWindow", "Correct Answer:"))
        self.set_homework_correct_answer_input.setPlaceholderText(_translate("MainWindow", "Correct Answer"))
        self.label_13.setText(_translate("MainWindow", "Incorrect Answer 1:"))
        self.set_homework_answer_b_input.setPlaceholderText(_translate("MainWindow", "Incorrect Answer"))
        self.label_18.setText(_translate("MainWindow", "Incorrect Answer 2:"))
        self.set_homework_answer_c_input.setPlaceholderText(_translate("MainWindow", "Incorrect Answer"))
        self.label_19.setText(_translate("MainWindow", "Incorrect Answer 3:"))
        self.set_homework_answer_d_input.setPlaceholderText(_translate("MainWindow", "Incorrect Answer"))
        self.set_homework_add_custom_question_button.setText(_translate("MainWindow", "Add Custom Question"))
        self.set_homework_custom_question_added_output.setText(_translate("MainWindow", "Question Added"))
        self.set_homework_tab_widget.setTabText(self.set_homework_tab_widget.indexOf(self.tab_2), _translate("MainWindow", "Add Custom Question"))
        self.label_7.setText(_translate("MainWindow", "Question:"))
        self.set_homework_question_label.setText(_translate("MainWindow", "Question Text"))
        self.label_5.setText(_translate("MainWindow", "Answer:"))
        self.set_homework_answer_label.setText(_translate("MainWindow", "Correct Answer"))
        self.set_homework_remove_question_button.setText(_translate("MainWindow", "REMOVE QUESTION"))
        self.set_homework_removed_output.setText(_translate("MainWindow", "Question Removed"))
        self.set_homework_tab_widget.setTabText(self.set_homework_tab_widget.indexOf(self.tab_3), _translate("MainWindow", "Remove Question"))
        self.label_16.setText(_translate("MainWindow", "Create Class:"))
        self.admin_class_input.setPlaceholderText(_translate("MainWindow", "Class Name"))
        self.admin_create_class_submit_button.setText(_translate("MainWindow", "Submit"))
        self.admin_create_class_status_label.setText(_translate("MainWindow", "Create class status"))
        self.label_14.setText(_translate("MainWindow", "Manage Class:"))
        self.admin_class_user_combo_box.setItemText(0, _translate("MainWindow", "Class"))
        self.admin_username_input.setPlaceholderText(_translate("MainWindow", "Username"))
        self.admin_username_submit_button.setText(_translate("MainWindow", "Submit"))
        self.admin_add_user_status_label.setText(_translate("MainWindow", "Add user status"))
        self.admin_tab_widget.setTabText(self.admin_tab_widget.indexOf(self.tab_5), _translate("MainWindow", "Add User"))
        self.admin_username_combo_box.setItemText(0, _translate("MainWindow", "Username"))
        self.admin_remove_user_button.setText(_translate("MainWindow", "REMOVE"))
        self.admin_remove_user_status_label.setText(_translate("MainWindow", "Remove user status"))
        self.admin_tab_widget.setTabText(self.admin_tab_widget.indexOf(self.tab_4), _translate("MainWindow", "Remove User"))
        self.label_42.setText(_translate("MainWindow", "Homework Name:"))
        self.admin_homework_name_input.setPlaceholderText(_translate("MainWindow", "Homework Name"))
        self.label_3.setText(_translate("MainWindow", "Description"))
        self.admin_homework_description_input.setPlaceholderText(_translate("MainWindow", "Homework Description"))
        self.label_43.setText(_translate("MainWindow", "Due Date:"))
        self.admin_add_homework_button.setText(_translate("MainWindow", "Add Homework"))
        self.admin_add_homework_status_output.setText(_translate("MainWindow", "Homework Added"))
        self.admin_tab_widget.setTabText(self.admin_tab_widget.indexOf(self.tab_6), _translate("MainWindow", "Add Homework"))
        self.admin_remove_homework_combo_box.setItemText(0, _translate("MainWindow", "Homework"))
        self.admin_remove_homework_button.setText(_translate("MainWindow", "REMOVE"))
        self.admin_remove_homework_status_label.setText(_translate("MainWindow", "Remove homework status"))
        self.admin_tab_widget.setTabText(self.admin_tab_widget.indexOf(self.tab_7), _translate("MainWindow", "Remove Homework"))
        self.label_20.setText(_translate("MainWindow", "Delete Class:"))
        self.admin_delete_class_combo_box.setItemText(0, _translate("MainWindow", "Class"))
        self.admin_remove_class_button.setText(_translate("MainWindow", "REMOVE"))
        self.admin_delete_class_status_label.setText(_translate("MainWindow", "Delete class status"))
        self.account_management_first_name_label.setText(_translate("MainWindow", "New First Name"))
        self.account_management_first_name_input.setPlaceholderText(_translate("MainWindow", "First Name"))
        self.account_management_last_name_label.setText(_translate("MainWindow", "New Last Name"))
        self.account_management_last_name_input.setPlaceholderText(_translate("MainWindow", "Last Name"))
        self.account_management_old_password_label.setText(_translate("MainWindow", "Current Password:"))
        self.account_management_old_password_input.setPlaceholderText(_translate("MainWindow", "Current Password"))
        self.account_management_new_password_label.setText(_translate("MainWindow", "New Password"))
        self.account_management_new_password_input.setPlaceholderText(_translate("MainWindow", "New Password"))
        self.account_management_verify_new_password_label.setText(_translate("MainWindow", "Verify New Password:"))
        self.account_management_new_password_verify_input.setPlaceholderText(_translate("MainWindow", "Verify New Password"))
        self.account_management_submit_button.setText(_translate("MainWindow", "Submit"))
        self.account_management_success_output.setText(_translate("MainWindow", "Result"))
        self.label_15.setText(_translate("MainWindow", "View Type:"))
        self.view_classes_view_type_combo_box.setItemText(0, _translate("MainWindow", "Class View"))
        self.view_classes_view_type_combo_box.setItemText(1, _translate("MainWindow", "Student View"))
        self.label_17.setText(_translate("MainWindow", "Class:"))
        self.view_classes_display_type_output.setText(_translate("MainWindow", "Homework/Student:"))
        self.view_classes_score_table.setSortingEnabled(True)
        self.label_2.setText(_translate("MainWindow", "Joe Down"))


from PyQt5.QtChart import QChartView
import window_rc
